---
kind: pipeline
name: linux-amd64
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: briandowns/rancher-build-base:v0.1.1
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 20 # wait for docker availability
  - TAG=${DRONE_TAG} make image-build
  when:
    event:
    - push

- name: push
  image: briandowns/rancher-build-base:v0.1.1
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - TAG=${DRONE_TAG} make image-push
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - tag

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
  - name: dockersock
    temp: {}
